version: "3"

services:
  farcaster-node:
    image: ubuntu:22.04

    container_name: farcaster-node

    restart: unless-stopped

    ports:
      - "2283:2283"

    volumes:
      - ../data:/data
      - ../logs:/logs

    command: tail -f /dev/null
